### PR TITLE
URL fallback option

### PR DESCRIPTION
**Pull request by ekerkenaar**
I have added fallback option (for those who use Windows) to use the absolute URL when no relativeUrl is available.

Any questions and comment are welcome...

### CODE REVIEW

**Comment by jtrussell** [comment]
Ah sorry, [it looks like](https://docs.angularjs.org/api/ngResource/service/$resource) the "Relative URL" property is new as of svn version 1.8. You should be alright on Windows with 1.8 but I agree we should use a different property or have a fallback to at least support 1.7, so we'd welcome a PR.

Do you mind cleaning up the styles (please indent with spaces, not tabs) and leaving off the webstorm folder from the ignore list?

**Comment by ekerkenaar** [comment]
Of course, that's no problem. I forgot to check the coding style (sorry about that).
I'll get back to you with another PR.

**Comment by ekerkenaar** [comment]
Thank you for pointing out that svn 1.7 does not use the relative url property. I should really update my svn client...

Anyway, I have updated my fork by removing my earlier commits and committing/pushing the changes you requested.

**Comment by jtrussell** [comment]
Thanks! The changes should be available in v0.7.1.

**Pull request merged**
